---
title: "Extracting structured data from papers using LLM"
author: 
  - name: Marian Klose
    orcid: 0009-0005-1706-6289
    email: marian.klose@fu-berlin.de
    affiliations:
      - name: Freie Universität Berlin
date: now
callout-appearance: minimal
execute:
  enabled: true
  echo: true
  message: true
  warning: true
format:
  html:
    toc: true
    number-sections: true
    embed-resources: true
---


This notebook shows a proof of concept how to use a large language model (LLM) to extract structured data about the underlying model from NLME publications.

## Preamble

In [1]:
# load packages
import pandas as pd
import json
from openai import OpenAI
from pydantic import BaseModel, Field
from typing import Optional
from enum import Enum

## General settings

We go for the cheapest model `gpt-5-nano` to keep the costs low. The costs per 1M tokens are defined so that the total costs can be calculated later on.

In [2]:
# define gpt model
gpt_model = "gpt-5-nano"

# define input and output costs (https://platform.openai.com/docs/pricing?latest-pricing=standard)
input_cost_pertoken_usd = 0.005/1_000_000  # cost per token for input
output_cost_pertoken_usd = 0.40/1_000_000  # cost per token for output

# define number of papers to process
n_papers = 200

## Read in data

We read back in the previously saved (enriched) PMC query results including abstract and full body text.

In [3]:
# read in json file with enriched article records
articles = pd.read_json("out/pmc_query_results_enriched.json", orient="records")

# show articles with prettyr print
articles.head()

,PMID,Title,Authors,Citation,First Author,Journal/Book,Publication Year,Create Date,PMCID,NIHMS ID,DOI,Abstract,Body
0,40687901,Pharmacokinetics and Safety with Bioequivalenc...,"Wu B, Wang W, Zhang Q, Yu G, Lin J, Zhang T, Y...",Drug Des Devel Ther. 2025 Jul 14;19:6025-6035....,Wu B,Drug Des Devel Ther,2025,2025/07/21,PMC12274271,None,10.2147/DDDT.S508202,PURPOSE: Isosorbide mononitrate was recommende...,pmc Drug Des Devel Ther Drug Des Devel Ther 95...
1,32034814,Evaluation of pharmacokinetics and safety with...,"Wang T, Wang Y, Lin S, Fang L, Lou S, Zhao D, ...",J Clin Lab Anal. 2020 Jun;34(6):e23228. doi: 1...,Wang T,J Clin Lab Anal,2020,2020/02/09,PMC7307347,None,10.1002/jcla.23228,"BACKGROUND AND OBJECTIVE: Amlodipine, a main s...",J Clin Lab Anal J. Clin. Lab. Anal 3636 jclinl...
2,30710324,Systemic Bioequivalence Is Unlikely to Equal T...,"Au JL, Lu Z, Abbiati RA, Wientjes MG.",AAPS J. 2019 Feb 1;21(2):24. doi: 10.1208/s122...,Au JL,AAPS J,2019,2019/02/03,PMC6432930,NIHMS1009981,10.1208/s12248-019-0296-z,Approval of generic drugs by the US Food and D...,AAPS J AAPS J 319 nihpa The AAPS journal 1550-...
3,40781573,Assessment of Pharmacokinetics and Safety with...,"Fu Q, Huang C, Yuan Y, Wang Y, Zhu B, Liu Y, T...",Drugs R D. 2025 Sep;25(3):263-274. doi: 10.100...,Fu Q,Drugs R D,2025,2025/08/09,PMC12460201,None,10.1007/s40268-025-00519-4,"BACKGROUND AND OBJECTIVE: Nitroglycerin, a cor...",pmc Drugs R D Drugs R D 2559 drugsrd Drugs in ...
4,24151591,Pharmacokinetics and bioequivalence evaluation...,"Brioschi TM, Schramm SG, Kano EK, Koono EE, Ch...",Biomed Res Int. 2013;2013:281392. doi: 10.1155...,Brioschi TM,Biomed Res Int,2013,2013/10/24,PMC3787571,None,10.1155/2013/281392,The purpose of this study was to investigate c...,Biomed Res Int Biomed Res Int 2029 bmri BMRI B...

## Initialize OpenAI client

A client for the OpenAI API is initialized using an API key stored as an environment variable.

In [4]:
# initialize openai client
client = OpenAI()

## Assess suitability of publications

The first task is to assess whether a publication is suitable for data extraction. Publications are suitable if they report a single population pharmacokinetic model. Other types of publications (reviews, tutorials, or studies reporting multiple models) are probably too complex to be handled by the LLM in a reliable way.

### Define structured output classes

Structured output classes are defined using `pydantic`. The classes define the expected structure of the output data and help to validate the extracted information. More information can be found under https://platform.openai.com/docs/guides/structured-outputs.

In [5]:
# single class for suitability flag
class SuitableFlag(BaseModel):
    suitable: bool = Field(
        description='''
        Indicates if this paper reports a single bioequivalence trial (True). 
        If the article represents a comment, a perspective, a review, a correction, a retraction,
        or a meta-analysis, it is not suitable (False). It is also not suitable if 
        it tackles some methodological issue without reporting a specific trial. It has to report
        the results of a single bioequivalence trial.
        '''
    )

### Define system message

The system message defines the role of the LLM and provides general instructions on how to handle the task.

In [6]:
# define system message
system_message_flag = '''
You are a pharmacometric / clinical pharmacology expert. You will be provided with a title and abstract of a scientific publication. 
Your task is to classify whether the paper reports a single bioequivalence trial (True) or not. 
If the article represents a comment, a perspective, a review, a correction, a retraction,
or a meta-analysis, it is not suitable (False). It is also not suitable if 
it tackles some methodological issue without reporting a specific trial. It has to report
the results of a single bioequivalence trial.
''' 

# print
system_message_flag

'\nYou are a pharmacometric / clinical pharmacology expert. You will be provided with a title and abstract of a scientific publication. \nYour task is to classify whether the paper reports a single bioequivalence trial (True) or not. \nIf the article represents a comment, a perspective, a review, a correction, a retraction,\nor a meta-analysis, it is not suitable (False). It is also not suitable if \nit tackles some methodological issue without reporting a specific trial. It has to report\nthe results of a single bioequivalence trial.\n'

### Make requests to LLM

We now loop over all publications and make requests to the LLM to assess the suitability of each publication. The title and abstract are provided as context to the LLM. The responses are parsed and saved in a new column in the dataframe (suitable or not suitable).

In [7]:
# Initialize new columns
articles["Suitable"] = None
articles["InputTokensFlag"] = None
articles["OutputTokensFlag"] = None
articles["PriceUSDFlag"] = None

# Empty lists to track totals
input_tokens_flag = []
output_tokens_flag = []
prices_usd_flag = []

# loop over elements in list
for idx, row in articles.head(n_papers).iterrows():
    # message to user
    print(f"Processing article {idx+1}/{len(articles)}: {row['Title']}")
    
    # extract information
    title = row["Title"],
    abstract = row["Abstract"]
    
    # construct user message
    user_message = f'title: {title}\nabstract: {abstract}'
    
    # try to make request to chatgpt
    try:
        # make request
        response = client.responses.parse(
            model=gpt_model,
            input=[
                {"role": "system", "content": system_message_flag},
                {"role": "user", "content": user_message},
            ],
            text_format=SuitableFlag
        )
        
        # retrieve and print the response
        model_info = response.output_parsed
        print(f"> Suitable? {model_info.suitable}\n")
        
        # append tokens and prices to lists
        in_toks = response.usage.input_tokens
        out_toks = response.usage.output_tokens
        price = (in_toks * input_cost_pertoken_usd) + (out_toks * output_cost_pertoken_usd)
        
        # update lists
        input_tokens_flag.append(in_toks)
        output_tokens_flag.append(out_toks)
        prices_usd_flag.append(price)
        
        # update dataframe
        articles.at[idx, "Suitable"] = model_info.suitable
        articles.at[idx, "InputTokensFlag"] = in_toks
        articles.at[idx, "OutputTokensFlag"] = out_toks
        articles.at[idx, "PriceUSDFlag"] = price
        
    # catch exceptions
    except Exception as e:
        print(f"Error: {e}")
        
# define prices for these calls (in USD)
total_price_flag = sum(prices_usd_flag)
print(f"Total price for flagging {n_papers} papers: ${total_price_flag:.3f}")

Processing article 1/200: Pharmacokinetics and Safety with Bioequivalence of Isosorbide Mononitrate Sustained-Release Tablets in Chinese Healthy Volunteers: Bioequivalence Study

> Suitable? True

Processing article 2/200: Evaluation of pharmacokinetics and safety with bioequivalence of Amlodipine in healthy Chinese volunteers: Bioequivalence Study Findings

> Suitable? False

Processing article 3/200: Systemic Bioequivalence Is Unlikely to Equal Target Site Bioequivalence for Nanotechnology Oncologic Products

> Suitable? False

Processing article 4/200: Assessment of Pharmacokinetics and Safety with Bioequivalence of the Nitroglycerin Sublingual Tablets of Two Formulations in Chinese Healthy Subjects: A Bioequivalence Study

> Suitable? True

Processing article 5/200: Pharmacokinetics and bioequivalence evaluation of cyclobenzaprine tablets

> Suitable? True

Processing article 6/200: Evaluation of Pharmacokinetics and Safety with Bioequivalence of Ibuprofen Sustained-Release Capsules of Two Formulations, in Chinese Healthy Volunteers: Bioequivalence Study

> Suitable? False

Processing article 7/200: Bioequivalence of generic and branded amoxicillin capsules in healthy human volunteers

> Suitable? True

Processing article 8/200: Bioequivalence: tried and tested

> Suitable? False

Processing article 9/200: Bioequivalence assessment of two formulations of ibuprofen

> Suitable? True

Processing article 10/200: Integrating In Vitro, Modeling, and In Vivo Approaches to Investigate Warfarin Bioequivalence

> Suitable? True

Processing article 11/200: Bioequivalence studies for levothyroxine

> Suitable? False

Processing article 12/200: Bioequivalence of orally administered generic, compounded, and innovator-formulated itraconazole in healthy dogs

> Suitable? True

Processing article 13/200: A Multi-centric Bioequivalence Trial in Ph+ Chronic Myeloid Leukemia Patients to Assess Bioequivalence and Safety Evaluation of Generic Imatinib Mesylate 400 mg Tablets

> Suitable? True

Processing article 14/200: Bioequivalence Study of Palbociclib Tablets in Healthy Volunteers

> Suitable? True

Processing article 15/200: Pharmacokinetics and bioequivalence of ranitidine and bismuth derived from two compound preparations

> Suitable? True

Processing article 16/200: Between-Batch Bioequivalence (BBE): a Statistical Test to Evaluate In Vitro Bioequivalence Considering the Between-Batch Variability

> Suitable? False

Processing article 17/200: Pharmacokinetics of oral pridinol: Results of a randomized, crossover bioequivalence trial in healthy subjects

> Suitable? True

Processing article 18/200: Pharmacodynamic Studies to Demonstrate Bioequivalence of Oral Inhalation Products

> Suitable? False

Processing article 19/200: Current Bioequivalence Study Designs in South Korea: A Comprehensive Analysis of Bioequivalence Study Reports Between 2013 and 2019

> Suitable? False

Processing article 20/200: Bioequivalence of dispersed stavudine: opened versus closed capsule dosing

> Suitable? True

Processing article 21/200: Likelihood approach for evaluating bioequivalence of highly variable drugs

> Suitable? False

Processing article 22/200: Predictive Potential of C(max) Bioequivalence in Pilot Bioavailability/Bioequivalence Studies, through the Alternative ƒ(2) Similarity Factor Method

> Suitable? False

Processing article 23/200: Bioequivalence studies in Morocco

> Suitable? False

Processing article 24/200: Pharmacokinetics, Bioequivalence, and Safety Studies of Crisaborole Ointment in Healthy Chinese Subjects

> Suitable? True

Processing article 25/200: In silico prediction of bioequivalence of atorvastatin tablets based on GastroPlus™ software

> Suitable? False

Processing article 26/200: Multivariate Assessment for Bioequivalence Based on the Correlation of Random Effect

> Suitable? False

Processing article 27/200: An Update Review of Biosimilars of Adalimumab in Psoriasis - Bioequivalence and Interchangeability

> Suitable? False

Processing article 28/200: Assessing bioequivalence of generic modified-release antiepileptic drugs

> Suitable? False

Processing article 29/200: Focus on biosimilar etanercept - bioequivalence and interchangeability

> Suitable? False

Processing article 30/200: Pharmacokinetics and bioequivalence of 2 meloxicam oral dosage formulations in healthy adult horses

> Suitable? True

Processing article 31/200: Pharmacokinetic Bioequivalence of Two Inhaled Tiotropium Bromide Formulations in Healthy Volunteers

> Suitable? True

Processing article 32/200: A Comparative Pharmacokinetic Study of Fexuprazan 10 mg: Demonstrating Bioequivalence with the Reference Formulation and Evaluating Steady State

> Suitable? True

Processing article 33/200: Pharmacokinetics and Bioequivalence of Apremilast Tablets in Chinese Healthy Subjects Under Fasting and Postprandial States

> Suitable? False

Processing article 34/200: Open Flow Microperfusion as a Dermal Pharmacokinetic Approach to Evaluate Topical Bioequivalence

> Suitable? True

Processing article 35/200: Bioequivalence of inhaled medications

> Suitable? False

Processing article 36/200: Bioequivalence requirements in the European Union: critical discussion

> Suitable? False

Processing article 37/200: Bioequivalence; its history, practice, and future

> Suitable? False

Processing article 38/200: Evaluation of sex-by-formulation interaction in bioequivalence studies of efavirenz tablets

> Suitable? False

Processing article 39/200: Pharmacokinetics and bioequivalence of two imidocarb formulations in cattle after subcutaneous injection

> Suitable? True

Processing article 40/200: Bioequivalence evaluation of two 5% ceftiofur hydrochloride sterile suspension in pigs

> Suitable? True

Processing article 41/200: Pharmacokinetics and bioequivalence of a liquid formulation of hydroxyurea in children with sickle cell anemia

> Suitable? True

Processing article 42/200: Effects of cytokines on antiviral pharmacokinetics: an alternative approach to assessment of drug interactions using bioequivalence guidelines

> Suitable? False

Processing article 43/200: Pharmacokinetic and Bioequivalence Evaluation of Two Sitagliptin Tablets With Different Salts in Healthy Subjects

> Suitable? True

Processing article 44/200: Study on bioequivalence and influence of obesity-related indicators on pharmacokinetics and pharmacodynamics for insulin degludec in healthy subjects

> Suitable? True

Processing article 45/200: Bioequivalence evaluation of generic febuxostat versus Feburic(®) in healthy Chinese subjects: a randomized crossover study

> Suitable? True

Processing article 46/200: The Single-Dose Pharmacokinetics of a Compounded Levetiracetam Formulation and Bioequivalence to a Commercial Formulation in Healthy Dogs

> Suitable? True

Processing article 47/200: Bioequivalence of HX575 (recombinant human epoetin alfa) and a comparator epoetin alfa after multiple subcutaneous administrations

> Suitable? True

Processing article 48/200: Pharmacokinetics and bioequivalence of two cyclosporine oral solution formulations in cats

> Suitable? True

Processing article 49/200: Conversion from twice- to once-daily tacrolimus in pediatric kidney recipients: a pharmacokinetic and bioequivalence study

> Suitable? True

Processing article 50/200: Pharmacokinetic Bioequivalence, Safety, and Immunogenicity of DMB-3111, a Trastuzumab Biosimilar, and Trastuzumab in Healthy Japanese Adult Males: Results of a Randomized Trial

> Suitable? True

Processing article 51/200: Comparative bioequivalence studies of tramadol hydrochloride sustained-release 200 mg tablets

> Suitable? False

Processing article 52/200: Overview of the European Medicines Agency's Development of Product-Specific Bioequivalence Guidelines

> Suitable? False

Processing article 53/200: Bioequivalence of thyroid preparations: the final word?

> Suitable? False

Processing article 54/200: Acarbose bioequivalence: exploration of new pharmacodynamic parameters

> Suitable? True

Processing article 55/200: Bioequivalence of generic aerosol bronchodilators: what are the issues?

> Suitable? False

Processing article 56/200: Particle size and gastrointestinal absorption influence tiotropium pharmacokinetics: a pilot bioequivalence study of PUR0200 and Spiriva HandiHaler

> Suitable? True

Processing article 57/200: Bioequivalence of oxymorphone extended release and crush-resistant oxymorphone extended release

> Suitable? False

Processing article 58/200: A new hypothesis to investigate bioequivalence of pharmaceutical inhalation products

> Suitable? False

Processing article 59/200: Pharmacokinetic/pharmacodynamic assessment of a novel, pharmaceutical lipid-aspirin complex: results of a randomized, crossover, bioequivalence study

> Suitable? True

Processing article 60/200: Immunomodulation profile of the biosimilar trastuzumab MYL-1401O in a bioequivalence phase I study

> Suitable? True

Processing article 61/200: Bioequivalence of a new coated 15 mg primaquine formulation for malaria elimination

> Suitable? True

Processing article 62/200: Medroxyprogesterone acetate: steady-state pharmacokinetics bioequivalence of two oral formulations

> Suitable? True

Processing article 63/200: A Pharmacokinetic Bioequivalence Study of Fremanezumab Administered Subcutaneously Using an Autoinjector and a Prefilled Syringe

> Suitable? True

Processing article 64/200: Comparative pharmacokinetics and bioequivalence of 145-mg fenofibrate formulations in healthy Korean participants

> Suitable? True

Processing article 65/200: Saliva Versus Plasma Bioequivalence of Azithromycin in Humans: Validation of Class I Drugs of the Salivary Excretion Classification System

> Suitable? True

Processing article 66/200: Pharmacokinetic interactions between chloroquine, sulfadoxine and pyrimethamine and their bioequivalence in a generic fixed-dose combination in healthy volunteers in Uganda

> Suitable? True

Processing article 67/200: Bioequivalence Study of Tebipenem Pivoxil in Healthy Chinese Adults

> Suitable? True

Processing article 68/200: Sequential bioequivalence approaches for parallel designs

> Suitable? False

Processing article 69/200: A survey of the likelihood approach to bioequivalence trials

> Suitable? False

Processing article 70/200: Bioequivalence Between Generic and Branded Lamotrigine in People With Epilepsy: The EQUIGEN Randomized Clinical Trial

> Suitable? True

Processing article 71/200: Absolute Oral Bioavailability and Bioequivalence of LSD Base and Tartrate in a Double-Blind, Placebo-Controlled, Crossover Study

> Suitable? True

Processing article 72/200: Regulatory utility of mechanistic modeling to support alternative bioequivalence approaches: A workshop overview

> Suitable? False

Processing article 73/200: Pharmacokinetics and bioequivalence evaluation of lenalidomide in Chinese patients with multiple myeloma

> Suitable? True

Processing article 74/200: Steady state bioequivalence of generic and innovator formulations of stavudine, lamivudine, and nevirapine in HIV-infected Ugandan adults

> Suitable? True

Processing article 75/200: Pharmacokinetic and Bioequivalence Study of Eldecalcitol Soft Capsules in Healthy Chinese Subjects

> Suitable? False

Processing article 76/200: Challenges and opportunities in achieving bioequivalence for fixed-dose combination products

> Suitable? False

Processing article 77/200: Bioequivalence study of two formulations of bisoprolol fumarate film-coated tablets in healthy subjects

> Suitable? True

Processing article 78/200: Single-Dose Bioequivalence of Two Mini Nicotine Lozenge Formulations

> Suitable? True

Processing article 79/200: A Pharmacokinetic Bioequivalence Study Comparing Pirfenidone Tablet and Capsule Dosage Forms in Healthy Adult Volunteers

> Suitable? True

Processing article 80/200: The Effect Of Food On The Pharmacokinetic Properties And Bioequivalence Of Two Formulations Of Levocetirizine Dihydrochloride In Healthy Chinese Volunteers

> Suitable? True

Processing article 81/200: Pharmacokinetics, Bioequivalence and Safety Evaluation of Two Ticagrelor Tablets Under Fasting and Fed Conditions in Healthy Chinese Subjects

> Suitable? True

Processing article 82/200: Bioequivalence of two esomeprazole magnesium enteric-coated formulations in healthy Chinese subjects

> Suitable? True

Processing article 83/200: Pharmacokinetics and Bioequivalence of a Novel Extended-Release Formulation of Methylphenidate Hydrochloride for Attention-Deficit/Hyperactivity Disorder

> Suitable? False

Processing article 84/200: Modern methods for analysis of antiepileptic drugs in the biological fluids for pharmacokinetics, bioequivalence and therapeutic drug monitoring

> Suitable? False

Processing article 85/200: Comparative study on the bioavailability and bioequivalence of rifapentine capsules in humans

> Suitable? True

Processing article 86/200: Summary workshop report: bioequivalence, biopharmaceutics classification system, and beyond

> Suitable? False

Processing article 87/200: A single-dose, four-cycle, fully repetitive crossover bioequivalence of dabigatran etexilate in Chinese

> Suitable? False

Processing article 88/200: Metrics for the evaluation of bioequivalence of modified-release formulations

> Suitable? False

Processing article 89/200: Clinical Bioequivalence of Wixela Inhub and Advair Diskus in Adults With Asthma

> Suitable? True

Processing article 90/200: PBPK Modeling to Support Bioavailability and Bioequivalence Assessment in Pediatric Populations

> Suitable? False

Processing article 91/200: Bioequivalence and population pharmacokinetic modeling of two forms of antibiotic, cefuroxime lysine and cefuroxime sodium, after intravenous infusion in beagle dogs

> Suitable? True

Processing article 92/200: Pharmacokinetics and Bioequivalence of Isavuconazole Administered as Isavuconazonium Sulfate Intravenous Solution via Nasogastric Tube or Orally in Healthy Subjects

> Suitable? True

Processing article 93/200: Current methodology to assess bioequivalence of levothyroxine sodium products is inadequate

> Suitable? False

Processing article 94/200: Evaluation of Ornidazole Tablets Bioequivalence in Chinese Healthy Participants Under Fasted and Fed Conditions Using Pharmacokinetic Parameters

> Suitable? False

Processing article 95/200: Sample size determination for individual bioequivalence inference

> Suitable? False

Processing article 96/200: Evaluation of bioequivalence of two oral formulations of olanzapine

> Suitable? True

Processing article 97/200: Short Communication: Bioequivalence of Tenofovir and Emtricitabine After Coencapsulation with the Proteus Ingestible Sensor

> Suitable? True

Processing article 98/200: Bioequivalence of oral and intravenous carbamazepine formulations in adult patients with epilepsy

> Suitable? True

Processing article 99/200: Pharmacokinetics and bioequivalence assessment of optimized directly compressible Aceclofenac (100 mg) tablet formulation in healthy human subjects

> Suitable? True

Processing article 100/200: Comparative Pharmacokinetics and Bioequivalence of Pour-On Ivermectin Formulations in Korean Hanwoo Cattle

> Suitable? True

Processing article 101/200: Pharmacokinetics of EDP-420 after multiple oral doses in healthy adult volunteers and in a bioequivalence study

> Suitable? False

Processing article 102/200: Pharmacokinetics and bioequivalence evaluation of omeprazole and sodium bicarbonate dry suspensions in healthy Chinese volunteers

> Suitable? True

Processing article 103/200: Highly variable drugs: observations from bioequivalence data submitted to the FDA for new generic drug applications

> Suitable? False

Processing article 104/200: A comparison of the bioequivalence of two formulations of epoetin alfa after subcutaneous injection

> Suitable? False

Processing article 105/200: Comparative bioequivalence study between a novel matrix transdermal delivery system of fentanyl and a commercially available reservoir formulation

> Suitable? True

Processing article 106/200: Demonstrating Bioequivalence for a Lumacaftor Monosubstance Formulation Versus Orkambi(®) (Lumacaftor/Ivacaftor) in Healthy Subjects

> Suitable? True

Processing article 107/200: Sample size determination in bioequivalence studies using statistical assurance

> Suitable? False

Processing article 108/200: Fluorescence detection of tramadol in healthy Chinese volunteers by high-performance liquid chromatography and bioequivalence assessment

> Suitable? True

Processing article 109/200: Physiologically based absorption modeling to predict the bioequivalence of two apixaban formulations

> Suitable? False

Processing article 110/200: Evaluation of the highly variable agomelatine pharmacokinetics in Chinese healthy subjects to support bioequivalence study

> Suitable? False

Processing article 111/200: New questions regarding bioequivalence of levothyroxine preparations: a clinician's response

> Suitable? False

Processing article 112/200: Bioequivalence study of two formulations of candesartan cilexetil tablet in healthy subjects under fasting conditions

> Suitable? True

Processing article 113/200: Bioequivalence of eslicarbazepine acetate from two different sources of its active product ingredient in healthy subjects

> Suitable? True

Processing article 114/200: Limited-sampling strategy models for itraconazole and hydroxy-itraconazole based on data from a bioequivalence study

> Suitable? True

Processing article 115/200: TSH-based protocol, tablet instability, and absorption effects on L-T4 bioequivalence

> Suitable? False

Processing article 116/200: Bioequivalence Study of Two Formulations of Flunarizine Hydrochloride Capsules in Healthy Chinese Subjects Under Fasting and Fed Conditions

> Suitable? False

Processing article 117/200: Pharmacokinetics and Safety Evaluation of a New Generic Sitafloxacin: A Phase I Bioequivalence Study in Healthy Chinese Participants

> Suitable? False

Processing article 118/200: Bioequivalence Study of Amitriptyline Hydrochloride Tablets in Healthy Chinese Volunteers Under Fasting and Fed Conditions

> Suitable? False

Processing article 119/200: Evaluation of model-based bioequivalence approach for single sample pharmacokinetic studies

> Suitable? False

Processing article 120/200: Comparative assessment of saliva and plasma for drug bioavailability and bioequivalence studies in humans

> Suitable? False

Processing article 121/200: Non-bioequivalence of sublingual nifedipine

> Suitable? True

Processing article 122/200: Pharmacokinetic and bioequivalence study between two formulations of S-1 in Korean gastric cancer patients

> Suitable? True

Processing article 123/200: Pharmacokinetics and bioequivalence evaluation of two fixed-dose tablet formulations of dihydroartemisinin and piperaquine in Vietnamese subjects

> Suitable? True

Processing article 124/200: Bioavailability and Bioequivalence in Drug Development

> Suitable? False

Processing article 125/200: A Bayesian framework for virtual comparative trials and bioequivalence assessments

> Suitable? False

Processing article 126/200: A Proton Pump Inhibitor in the Reformulation Setting: Bioequivalence and Potential Implications for Long-Term Safety

> Suitable? False

Processing article 127/200: Bioequivalence and Pharmacokinetic Evaluation Study of Acetaminophen vs. Acetaminophen Plus Caffeine Tablets in Healthy Mexican Volunteers

> Suitable? True

Processing article 128/200: Assessment of the predictive capability of modelling and simulation to determine bioequivalence of inhaled drugs: A systematic review

> Suitable? False

Processing article 129/200: Physiologically based absorption modeling to predict the bioequivalence of two cilostazol formulations

> Suitable? False

Processing article 130/200: Pharmacokinetic properties and bioequivalence of gefitinib 250 mg in healthy Korean male subjects

> Suitable? True

Processing article 131/200: International Guidelines for Bioequivalence of Locally Acting Orally Inhaled Drug Products: Similarities and Differences

> Suitable? False

Processing article 132/200: Survey of international regulatory bioequivalence recommendations for approval of generic topical dermatological drug products

> Suitable? False

Processing article 133/200: Bioequivalence Study of Vortioxetine Hydrobromide Tablets in Healthy Chinese Subjects Under Fasting and Fed Conditions

> Suitable? False

Processing article 134/200: Therapeutic equivalence requires pharmaceutical, pharmacokinetic, and pharmacodynamic identities: true bioequivalence of a generic product of intravenous metronidazole

> Suitable? False

Processing article 135/200: A 2-Part, Open-Label, Phase 1 Bioequivalence and Food-Effect Study of Ubrogepant in Healthy Adult Participants

> Suitable? True

Processing article 136/200: Pharmacokinetics, bioavailability, and bioequivalence of lower-sodium oxybate in healthy participants in two open-label, randomized, crossover studies

> Suitable? False

Processing article 137/200: Bioequivalence between innovator and generic tacrolimus in liver and kidney transplant recipients: A randomized, crossover clinical trial

> Suitable? True

Processing article 138/200: Evaluation of a Scenario in Which Estimates of Bioequivalence Are Biased and a Proposed Solution: tlast (Common)

> Suitable? False

Processing article 139/200: Bioequivalence of two oral formulations of tebipenem pivoxil hydrobromide in healthy subjects

> Suitable? True

Processing article 140/200: Bioequivalence of a Fixed-Dose Combination Tablet of the Complete Two-Drug Regimen of Dolutegravir and Rilpivirine for Treatment of HIV-1 Infection

> Suitable? True

Processing article 141/200: Formulation and bioequivalence studies of choline alfoscerate tablet comparing with soft gelatin capsule in healthy male volunteers

> Suitable? True

Processing article 142/200: In Vitro Dissolution and in Silico Modeling Shortcuts in Bioequivalence Testing

> Suitable? False

Processing article 143/200: Bioequivalence of two tablet formulations of cefpodoxime proxetil in beagle dogs

> Suitable? True

Processing article 144/200: Pharmacokinetics and Bioequivalence Evaluation of Two Montelukast Sodium Chewable Tablets in Healthy Chinese Volunteers Under Fasted and Fed Conditions

> Suitable? False

Processing article 145/200: Preparation of altrenogest soft capsules and their bioequivalence in gilts

> Suitable? True

Processing article 146/200: Bioequivalence Evaluation of Two Formulations of Tenofovir Alafenamide Tablets in Healthy Subjects Under Fasting and Fed Conditions

> Suitable? False

Processing article 147/200: Allicin Bioavailability and Bioequivalence from Garlic Supplements and Garlic Foods

> Suitable? True

Processing article 148/200: Lack of pharmacokinetic bioequivalence between generic and branded amoxicillin formulations. A post-marketing clinical study on healthy volunteers

> Suitable? True

Processing article 149/200: Open-Label, Phase I, Pharmacokinetic Studies in Healthy Chinese Subjects to Evaluate the Bioequivalence and Food Effect of a Novel Formulation of Abiraterone Acetate Tablets

> Suitable? True

Processing article 150/200: Bioequivalence study of modified-release gliclazide tablets in healthy volunteers

> Suitable? True

Processing article 151/200: An In Silico Approach toward the Appropriate Absorption Rate Metric in Bioequivalence

> Suitable? False

Processing article 152/200: Association of Variability and Pharmacogenomics With Bioequivalence of Gefitinib in Healthy Male Subjects

> Suitable? False

Processing article 153/200: Pharmacokinetic bioequivalence of the fixed-dose combination of pertuzumab and trastuzumab administered subcutaneously using a handheld syringe or an on-body delivery system

> Suitable? True

Processing article 154/200: Pharmacokinetics and Bioequivalence of a Generic Ticagrelor 90-mg Formulation Versus the Innovator Product in Healthy White Subjects Under Fasting Conditions

> Suitable? True

Processing article 155/200: Bioequivalence Study of Rivastigmine 6 mg Capsules (Single Dose) in Healthy Volunteers

> Suitable? True

Processing article 156/200: Bioequivalence and Bioavailability of an Orodispersible Tablet of Sildenafil Citrate in Healthy Chinese Male Subjects

> Suitable? True

Processing article 157/200: Pharmacokinetics and Bioequivalence of Two Empagliflozin, with Evaluation in Healthy Jordanian Subjects under Fasting and Fed Conditions

> Suitable? False

Processing article 158/200: A comparative evaluation of bioequivalence of Gan & Lee glargine U300 and Toujeo(®) in Chinese healthy male participants

> Suitable? True

Processing article 159/200: Bioequivalence of Aripiprazole Oral Soluble Films and Orally Disintegrating Tablets in Healthy Participants: A Crossover Study

> Suitable? True

Processing article 160/200: Bioequivalence and tolerability assessment of a novel intravenous ciclosporin lipid emulsion compared to branded ciclosporin in Cremophor ® EL

> Suitable? True

Processing article 161/200: Exploration of the potential impact of batch-to-batch variability on the establishment of pharmacokinetic bioequivalence for inhalation powder drug products

> Suitable? False

Processing article 162/200: Evaluation of the Bioequivalence of Acarbose in Healthy Chinese People

> Suitable? False

Processing article 163/200: Pharmacokinetics and Bioequivalence of Two Fixed-Dose Combination Tablets of Valsartan/Amlodipine (80/5 Mg) in Healthy Chinese Subjects

> Suitable? True

Processing article 164/200: Pharmacokinetics and Safety of Estradiol Valerate Tablet and Its Generic: A Phase 1 Bioequivalence Study in Healthy Chinese Postmenopausal Female Subjects

> Suitable? True

Processing article 165/200: Stratum Corneum Sampling to Assess Bioequivalence between Topical Acyclovir Products

> Suitable? False

Processing article 166/200: Variability of Skin Pharmacokinetic Data: Insights from a Topical Bioequivalence Study Using Dermal Open Flow Microperfusion

> Suitable? True

Processing article 167/200: Journal impact factors: a 'bioequivalence' issue?

> Suitable? False

Processing article 168/200: In vitro considerations to support bioequivalence of locally acting drugs in dry powder inhalers for lung diseases

> Suitable? False

Processing article 169/200: Bioequivalence of HX575 (recombinant human epoetin alfa) and a comparator epoetin alfa after multiple intravenous administrations: an open-label randomised controlled trial

> Suitable? True

Processing article 170/200: The steady-state serum concentration of genistein aglycone is affected by formulation: a bioequivalence study of bone products

> Suitable? True

Processing article 171/200: Adjusted indirect comparisons to assess bioequivalence between generic clopidogrel products in Serbia

> Suitable? False

Processing article 172/200: Application of absorption modeling to predict bioequivalence outcome of two batches of etoricoxib tablets

> Suitable? True

Processing article 173/200: Bioequivalence and Pharmacokinetics of Low-Dose Anagrelide 0.5 mg Capsules in Healthy Volunteers

> Suitable? True

Processing article 174/200: An In Vitro-In Vivo Simulation Approach for the Prediction of Bioequivalence

> Suitable? False

Processing article 175/200: Batch-to-batch pharmacokinetic variability confounds current bioequivalence regulations: A dry powder inhaler randomized clinical trial

> Suitable? True

Processing article 176/200: Bioequivalence evaluation of epinephrine autoinjectors with attention to rapid delivery

> Suitable? True

Processing article 177/200: A study on the pharmacokinetic bioequivalence of oral tablet formulations of riluzole among healthy volunteers utilizing HPLC-MS/MS

> Suitable? True

Processing article 178/200: Effect of excipients on the particle size of precipitated pioglitazone in the gastrointestinal tract: impact on bioequivalence

> Suitable? True

Processing article 179/200: Adjustment of the area under the concentration curve by terminal rate constant for bioequivalence assessment in a parallel-group study of lamotrigine

> Suitable? True

Processing article 180/200: Saliva versus plasma bioequivalence of rusovastatin in humans: validation of class III drugs of the salivary excretion classification system

> Suitable? False

Processing article 181/200: Bioequivalence of recombinant factor VIII products: a position paper from the Italian Association of Hemophilia Centers

> Suitable? False

Processing article 182/200: Pharmacokinetics and bioequivalence of Withania somnifera (Ashwagandha) extracts - A double blind, crossover study in healthy adults

> Suitable? True

Processing article 183/200: Formulation and bioequivalence of two valsartan tablets after a single oral administration

> Suitable? True

Processing article 184/200: Pharmacogenetic Variants Associated with Fluoxetine Pharmacokinetics from a Bioequivalence Study in Healthy Subjects

> Suitable? True

Processing article 185/200: Development and comparison of model-integrated evidence approaches for bioequivalence studies with pharmacokinetic end points

> Suitable? False

Processing article 186/200: Bioequivalence of perampanel fine granules and tablets in healthy Japanese subjects

> Suitable? True

Processing article 187/200: 10th Anniversary of a Two-Stage Design in Bioequivalence. Why Has it Still Not Been Implemented?

> Suitable? False

Processing article 188/200: Confocal Raman Spectroscopy for Assessing Bioequivalence of Topical Formulations

> Suitable? True

Processing article 189/200: Common deficiencies with bioequivalence submissions in abbreviated new drug applications assessed by FDA

> Suitable? False

Processing article 190/200: Bioequivalence and Pharmacokinetic Evaluation of Two Metformin Hydrochloride Tablets Under Fasting and Fed Conditions in Healthy Chinese Volunteers

> Suitable? True

Processing article 191/200: Bioequivalence study of two formulations of lurasidone film coated tablets in healthy subjects under fed conditions

> Suitable? True

Processing article 192/200: Bioequivalence and Food Effect Assessment of 2 Fixed-Dose Combination Formulations of Dolutegravir and Lamivudine

> Suitable? True

Processing article 193/200: Bioequivalence study of donepezil hydrochloride tablets in healthy male volunteers

> Suitable? True

Processing article 194/200: Bioequivalence and Food Effect Assessment of Two Fixed-Dose Combination Formulations of Telmisartan-Hydrochlorothiazide Tablets in Chinese Healthy Subjects

> Suitable? True

Processing article 195/200: Bioequivalence Design With Sampling Distribution Segments

> Suitable? False

Processing article 196/200: Bioequivalence and pharmacodynamics of a generic dabigatran etexilate capsule in healthy Chinese subjects under fasting and fed conditions

> Suitable? True

Processing article 197/200: Bioequivalence study of three ibuprofen formulations after single dose administration in healthy volunteers

> Suitable? True

Processing article 198/200: Comparative Pharmacokinetics, Bioequivalence and Safety Study of Two Recombinant Human Chorionic Gonadotropin Injections in Healthy Chinese Subjects

> Suitable? True

Processing article 199/200: Bioequivalence of oral products and the biopharmaceutics classification system: science, regulation, and public policy

> Suitable? False

Processing article 200/200: Bioequivalence study of fluticasone propionate nebuliser suspensions in healthy Chinese subjects

> Suitable? True

Total price for flagging 200 papers: $0.052

### Show updated dataframe

In [8]:
# show updated dataframe
articles.head(n_papers)

,PMID,Title,Authors,Citation,First Author,Journal/Book,Publication Year,Create Date,PMCID,NIHMS ID,DOI,Abstract,Body,Suitable,InputTokensFlag,OutputTokensFlag,PriceUSDFlag
0,40687901,Pharmacokinetics and Safety with Bioequivalenc...,"Wu B, Wang W, Zhang Q, Yu G, Lin J, Zhang T, Y...",Drug Des Devel Ther. 2025 Jul 14;19:6025-6035....,Wu B,Drug Des Devel Ther,2025,2025/07/21,PMC12274271,None,10.2147/DDDT.S508202,PURPOSE: Isosorbide mononitrate was recommende...,pmc Drug Des Devel Ther Drug Des Devel Ther 95...,True,766,1360,0.000548
1,32034814,Evaluation of pharmacokinetics and safety with...,"Wang T, Wang Y, Lin S, Fang L, Lou S, Zhao D, ...",J Clin Lab Anal. 2020 Jun;34(6):e23228. doi: 1...,Wang T,J Clin Lab Anal,2020,2020/02/09,PMC7307347,None,10.1002/jcla.23228,"BACKGROUND AND OBJECTIVE: Amlodipine, a main s...",J Clin Lab Anal J. Clin. Lab. Anal 3636 jclinl...,False,831,656,0.000267
2,30710324,Systemic Bioequivalence Is Unlikely to Equal T...,"Au JL, Lu Z, Abbiati RA, Wientjes MG.",AAPS J. 2019 Feb 1;21(2):24. doi: 10.1208/s122...,Au JL,AAPS J,2019,2019/02/03,PMC6432930,NIHMS1009981,10.1208/s12248-019-0296-z,Approval of generic drugs by the US Food and D...,AAPS J AAPS J 319 nihpa The AAPS journal 1550-...,False,597,272,0.000112
3,40781573,Assessment of Pharmacokinetics and Safety with...,"Fu Q, Huang C, Yuan Y, Wang Y, Zhu B, Liu Y, T...",Drugs R D. 2025 Sep;25(3):263-274. doi: 10.100...,Fu Q,Drugs R D,2025,2025/08/09,PMC12460201,None,10.1007/s40268-025-00519-4,"BACKGROUND AND OBJECTIVE: Nitroglycerin, a cor...",pmc Drugs R D Drugs R D 2559 drugsrd Drugs in ...,True,881,592,0.000241
4,24151591,Pharmacokinetics and bioequivalence evaluation...,"Brioschi TM, Schramm SG, Kano EK, Koono EE, Ch...",Biomed Res Int. 2013;2013:281392. doi: 10.1155...,Brioschi TM,Biomed Res Int,2013,2013/10/24,PMC3787571,None,10.1155/2013/281392,The purpose of this study was to investigate c...,Biomed Res Int Biomed Res Int 2029 bmri BMRI B...,True,607,336,0.000137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,32338459,Bioequivalence and pharmacodynamics of a gener...,"Li X, Liu L, Xu B, Xiang Q, Li Y, Zhang P, Wan...",Pharmacol Res Perspect. 2020 Apr;8(2):e00593. ...,Li X,Pharmacol Res Perspect,2020,2020/04/28,PMC7184321,None,10.1002/prp2.593,To assess bioequivalence of a generic dabigatr...,Pharmacol Res Perspect Pharmacol Res Perspect ...,True,762,720,0.000292
196,18959779,Bioequivalence study of three ibuprofen formul...,"Bramlage P, Goldis A.",BMC Pharmacol. 2008 Oct 29;8:18. doi: 10.1186/...,Bramlage P,BMC Pharmacol,2008,2008/10/31,PMC2613135,None,10.1186/1471-2210-8-18,BACKGROUND: This phase I study was designed to...,BMC Pharmacol 56 bmcphar BMC Pharmacology 1471...,True,687,400,0.000163
197,32099328,"Comparative Pharmacokinetics, Bioequivalence a...","Wang J, Yang T, Mei H, Yu X, Peng H, Wang R, C...",Drug Des Devel Ther. 2020 Jan 29;14:435-444. d...,Wang J,Drug Des Devel Ther,2020,2020/02/27,PMC6996485,None,10.2147/DDDT.S235064,OBJECTIVE: To evaluate the pharmacokinetics (P...,Drug Des Devel Ther Drug Des Devel Ther 958 dd...,True,751,400,0.000164
198,21775984,Bioequivalence of oral products and the biopha...,"Amidon KS, Langguth P, Lennernäs H, Yu L, Amid...",Clin Pharmacol Ther. 2011 Sep;90(3):467-70. do...,Amidon KS,Clin Pharmacol Ther,2011,2011/07/22,PMC3228645,NIHMS337891,10.1038/clpt.2011.109,The demonstration of bioequivalence (BE) is an...,Clin Pharmacol Ther 319 nihpa Clinical pharmac...,False,393,656,0.000264
199,39830354,Bioequivalence study of fluticasone propionate...,"Cheng F, Shen T, Zhang F, Lei C, Zhu Y, Luo G,...",Front Pharmacol. 2025 Jan 3;15:1452596. doi: 1...,Cheng F,Front Pharmacol,2025,2025/01/20,PMC11738769,None,10.3389/fphar.2024.1452596,BACKGROUND: Fluticasone propionate is a synthe...,pmc Front Pharmacol Front Pharmacol 1524 front...,True,912,656,0.000267

## Retrieve NLME model information

Now we can focus on the publications that were classified as suitable and try to extract structured information about the underlying NLME model.

### Filter dataframe

First, we filter the dataframe to only include publications that were classified as suitable.

In [9]:
# filter dataframe for suitable articles
articles_suitable = articles[articles["Suitable"] == True].reset_index(drop=True)

# show filtered dataframe
articles_suitable.head()

,PMID,Title,Authors,Citation,First Author,Journal/Book,Publication Year,Create Date,PMCID,NIHMS ID,DOI,Abstract,Body,Suitable,InputTokensFlag,OutputTokensFlag,PriceUSDFlag
0,40687901,Pharmacokinetics and Safety with Bioequivalenc...,"Wu B, Wang W, Zhang Q, Yu G, Lin J, Zhang T, Y...",Drug Des Devel Ther. 2025 Jul 14;19:6025-6035....,Wu B,Drug Des Devel Ther,2025,2025/07/21,PMC12274271,None,10.2147/DDDT.S508202,PURPOSE: Isosorbide mononitrate was recommende...,pmc Drug Des Devel Ther Drug Des Devel Ther 95...,True,766,1360,0.000548
1,40781573,Assessment of Pharmacokinetics and Safety with...,"Fu Q, Huang C, Yuan Y, Wang Y, Zhu B, Liu Y, T...",Drugs R D. 2025 Sep;25(3):263-274. doi: 10.100...,Fu Q,Drugs R D,2025,2025/08/09,PMC12460201,None,10.1007/s40268-025-00519-4,"BACKGROUND AND OBJECTIVE: Nitroglycerin, a cor...",pmc Drugs R D Drugs R D 2559 drugsrd Drugs in ...,True,881,592,0.000241
2,24151591,Pharmacokinetics and bioequivalence evaluation...,"Brioschi TM, Schramm SG, Kano EK, Koono EE, Ch...",Biomed Res Int. 2013;2013:281392. doi: 10.1155...,Brioschi TM,Biomed Res Int,2013,2013/10/24,PMC3787571,None,10.1155/2013/281392,The purpose of this study was to investigate c...,Biomed Res Int Biomed Res Int 2029 bmri BMRI B...,True,607,336,0.000137
3,28706331,Bioequivalence of generic and branded amoxicil...,"Pathak P, Pandit VA, Dhande PP.",Indian J Pharmacol. 2017 Mar-Apr;49(2):176-181...,Pathak P,Indian J Pharmacol,2017,2017/07/15,PMC5497440,None,10.4103/ijp.IJP_793_16,CONTEXT: The Medical Council of India urges do...,Indian J Pharmacol Indian J Pharmacol 979 ijph...,True,683,336,0.000138
4,22087062,Bioequivalence assessment of two formulations ...,"Al-Talla ZA, Akrawi SH, Tolley LT, Sioud SH, Z...",Drug Des Devel Ther. 2011;5:427-33. doi: 10.21...,Al-Talla ZA,Drug Des Devel Ther,2011,2011/11/17,PMC3210071,None,10.2147/DDDT.S24504,BACKGROUND: This study assessed the relative b...,"Drug Des Devel Ther 958 dddt Drug Design, Deve...",True,554,656,0.000265

### Define structured output classes

We now define a set of structured output classes to capture the relevant information about the NLME model. The classes are again defined using `pydantic` and include various fields for the fields of interest.

In [10]:
class AdministrationType(str, Enum):
    IV = "intravenous"
    ORAL = "oral"
    IM = "intramuscular"
    SC = "subcutaneous"
    OTHER = "other"
    NOT_REPORTED = "not reported"


class FormulationType(str, Enum):
    TABLET = "tablet"
    CAPSULE = "capsule"
    SOLUTION = "solution"
    SUSPENSION = "suspension"
    POWDER = "powder"
    OTHER = "other"
    NOT_REPORTED = "not reported"

class PKSummary(BaseModel):
    """Central tendency and dispersion for a PK parameter."""
    central_tendency: Optional[float] = Field(
        description="Mean or median of the PK parameter for the TEST product. "
                    "Enter numeric value, not rounded. Enter 'missing' if missing.",
    )
    central_tendency_type: Optional[str] = Field(
        description="Specify whether the central tendency is a 'mean' or 'median'. "
                    "Enter 'missing' if not reported."
    )
    central_tendency_unit: Optional[str] = Field(
        description="Unit of the central tendency (e.g., ng/mL, h, ng·h/mL). "
                    "Enter 'missing' if not provided."
    ) 
    dispersion: Optional[str] = Field(
        description="Numerical value for the dispersion. Range, IQR, SD, or CI associated with the PK parameter. E.g., '12-24', '4-9', '5', '15'."
                    "Enter 'missing' if not reported."
    )
    dispersion_type: Optional[str] = Field(
        description="Specify which type of dispersion it is (e.g., 'range', 'IQR'). "
                    "Enter 'missing' if not reported."
    )   
    dispersion_unit: Optional[str] = Field(
        description="Unit of the dispersion (e.g., ng/mL, h, ng·h/mL, %). "
                    "Enter 'missing' if not provided."
    )


class PKParameters(BaseModel):
    Cmax: PKSummary = Field(description="Cmax results for TEST formulation only. Fasting only if there are both fasting and fed results.")
    Tmax: PKSummary = Field(description="Tmax results for TEST formulation only.  Fasting only if there are both fasting and fed results.")
    AUC0_t: PKSummary = Field(description="AUC0-t results for TEST formulation only.  Fasting only if there are both fasting and fed results.")
    AUC0_inf: PKSummary = Field(description="AUC0-inf results for TEST formulation only.  Fasting only if there are both fasting and fed results.")


class BioequivalenceTrial(BaseModel):
    compound: str = Field(
        description="Name of the compound used in the bioequivalence trial."
    )
    
    administration_route: AdministrationType = Field(
        description="Route of administration (oral, IV, IM, etc.). "
                    "Enter 'not reported' if unavailable."
    )
    
    formulation: FormulationType = Field(
        description="Formulation type for the TEST product (tablet, capsule, etc.). "
                    "Enter 'not reported' if unavailable."
    )
    
    dose: Optional[float] = Field(
        description="Administered dose of the TEST product. Numeric only. "
                    "Enter 'missing' if not provided."
    )
    dose_unit: Optional[str] = Field(
        description="Unit of the dose (e.g., mg, mcg). Enter 'missing' if not provided."
    )
    
    number_of_patients: Optional[int] = Field(
        description="Total number of subjects included in the trial. "
                    "Enter 'missing' if not provided."
    )
    
    last_sample_time: Optional[str] = Field(
        description="Time of the last sample taken without unit (e.g., '24'). "
                    "Enter 'missing' if not provided."
    )
    
    last_sample_time_unit: Optional[str] = Field(
        description="Unit of the last sample time (e.g., 'h', 'days'). "
                    "Enter 'missing' if not provided."
    )

    pk_parameters: PKParameters = Field(
        description="Reported PK results (central tendency + dispersion) for TEST product only."
    )

### Define system message and user message

A different system message is defined for the new task.

In [11]:
# define system message
system_message_content = '''
You are a pharmacometric / clinical pharmacology expert at extracting structured information about bioequivalence trials from unstructured text. 
You will be provided with a scientific publication that reports a single bioequivalence trial. 
Your task is to extract key information about the published trial from the results section of that paper, such as
the compound name, administration route, formulation type, dose, number of patients, last sample time,
and PK parameters (Cmax, Tmax, AUC0-t, AUC0-inf) for the investigated test formulation only.
''' 

# print
system_message_content

'\nYou are a pharmacometric / clinical pharmacology expert at extracting structured information about bioequivalence trials from unstructured text. \nYou will be provided with a scientific publication that reports a single bioequivalence trial. \nYour task is to extract key information about the published trial from the results section of that paper, such as\nthe compound name, administration route, formulation type, dose, number of patients, last sample time,\nand PK parameters (Cmax, Tmax, AUC0-t, AUC0-inf) for the investigated test formulation only.\n'

### Make request to LLM

We now loop over the filtered dataframe `articles_suitable` and make requests to the LLM to extract structured information about the NLME model. Now we provide the (more costly) full body text as context to the LLM. The responses are parsed and saved as JSON.

In [12]:
# Initialize new columns
articles["InputTokensContent"] = None
articles["OutputTokensContent"] = None
articles["PriceUSDContent"] = None

# Empty lists to track totals
input_tokens_content = []
output_tokens_content = []
prices_usd_content = []

# list to collect all extracted model reports
model_reports = []

# loop over elements in list
for idx, row in articles_suitable.head(n_papers).iterrows():
    # message to user
    print(f"Processing article {idx+1}/{len(articles_suitable)}: {row['Title']}")
    
    # extract information (user message)
    user_message_content = row["Body"]
    
    # try to make request to chatgpt
    try:
        # make request
        response = client.responses.parse(
            model=gpt_model,
            input=[
                {"role": "system", "content": system_message_content},
                {"role": "user", "content": user_message_content},
            ],
            text_format=BioequivalenceTrial
        )
        
        # retrieve and print the response
        model_content = response.output_parsed
        
        # convert output to dict
        model_dict = model_content.model_dump()
        
        # add metadata from dataframe (identifiers etc.)
        model_dict.update({
            "pmid": row.get("PMID", None),
            "pmcid": row.get("PMCID", None),
            "year": row.get("Publication Year", None),
            "title": row.get("Title", None),
            "abstract": row.get("Abstract", None)
        })
        
        # append to model_reports list
        model_reports.append(model_dict)
        
        # print confirmation
        print(f"> Added to model reports.\n")
        
        # append tokens and prices to lists
        in_toks = response.usage.input_tokens
        out_toks = response.usage.output_tokens
        price = (in_toks * input_cost_pertoken_usd) + (out_toks * output_cost_pertoken_usd)
        
        # update lists
        input_tokens_content.append(in_toks)
        output_tokens_content.append(out_toks)
        prices_usd_content.append(price)
        
    # catch exceptions
    except Exception as e:
        print(f"Error: {e}")
        
# define prices for these calls (in USD)
total_price_content = sum(prices_usd_content)
print(f"Total price for extracting content from {len(articles_suitable)} papers: ${total_price_content:.3f}")

# save to json
output_path = "out/extracted_pk_information.json"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(model_reports, f, indent=2, ensure_ascii=False)

Processing article 1/114: Pharmacokinetics and Safety with Bioequivalence of Isosorbide Mononitrate Sustained-Release Tablets in Chinese Healthy Volunteers: Bioequivalence Study

> Added to model reports.

Processing article 2/114: Assessment of Pharmacokinetics and Safety with Bioequivalence of the Nitroglycerin Sublingual Tablets of Two Formulations in Chinese Healthy Subjects: A Bioequivalence Study

> Added to model reports.

Processing article 3/114: Pharmacokinetics and bioequivalence evaluation of cyclobenzaprine tablets

> Added to model reports.

Processing article 4/114: Bioequivalence of generic and branded amoxicillin capsules in healthy human volunteers

> Added to model reports.

Processing article 5/114: Bioequivalence assessment of two formulations of ibuprofen

> Added to model reports.

Processing article 6/114: Integrating In Vitro, Modeling, and In Vivo Approaches to Investigate Warfarin Bioequivalence

> Added to model reports.

Processing article 7/114: Bioequivalence of orally administered generic, compounded, and innovator-formulated itraconazole in healthy dogs

> Added to model reports.

Processing article 8/114: A Multi-centric Bioequivalence Trial in Ph+ Chronic Myeloid Leukemia Patients to Assess Bioequivalence and Safety Evaluation of Generic Imatinib Mesylate 400 mg Tablets

> Added to model reports.

Processing article 9/114: Bioequivalence Study of Palbociclib Tablets in Healthy Volunteers

> Added to model reports.

Processing article 10/114: Pharmacokinetics and bioequivalence of ranitidine and bismuth derived from two compound preparations

> Added to model reports.

Processing article 11/114: Pharmacokinetics of oral pridinol: Results of a randomized, crossover bioequivalence trial in healthy subjects

> Added to model reports.

Processing article 12/114: Bioequivalence of dispersed stavudine: opened versus closed capsule dosing

> Added to model reports.

Processing article 13/114: Pharmacokinetics, Bioequivalence, and Safety Studies of Crisaborole Ointment in Healthy Chinese Subjects

> Added to model reports.

Processing article 14/114: Pharmacokinetics and bioequivalence of 2 meloxicam oral dosage formulations in healthy adult horses

> Added to model reports.

Processing article 15/114: Pharmacokinetic Bioequivalence of Two Inhaled Tiotropium Bromide Formulations in Healthy Volunteers

> Added to model reports.

Processing article 16/114: A Comparative Pharmacokinetic Study of Fexuprazan 10 mg: Demonstrating Bioequivalence with the Reference Formulation and Evaluating Steady State

> Added to model reports.

Processing article 17/114: Open Flow Microperfusion as a Dermal Pharmacokinetic Approach to Evaluate Topical Bioequivalence

> Added to model reports.

Processing article 18/114: Pharmacokinetics and bioequivalence of two imidocarb formulations in cattle after subcutaneous injection

> Added to model reports.

Processing article 19/114: Bioequivalence evaluation of two 5% ceftiofur hydrochloride sterile suspension in pigs

> Added to model reports.

Processing article 20/114: Pharmacokinetics and bioequivalence of a liquid formulation of hydroxyurea in children with sickle cell anemia

> Added to model reports.

Processing article 21/114: Pharmacokinetic and Bioequivalence Evaluation of Two Sitagliptin Tablets With Different Salts in Healthy Subjects

> Added to model reports.

Processing article 22/114: Study on bioequivalence and influence of obesity-related indicators on pharmacokinetics and pharmacodynamics for insulin degludec in healthy subjects

> Added to model reports.

Processing article 23/114: Bioequivalence evaluation of generic febuxostat versus Feburic(®) in healthy Chinese subjects: a randomized crossover study

> Added to model reports.

Processing article 24/114: The Single-Dose Pharmacokinetics of a Compounded Levetiracetam Formulation and Bioequivalence to a Commercial Formulation in Healthy Dogs

> Added to model reports.

Processing article 25/114: Bioequivalence of HX575 (recombinant human epoetin alfa) and a comparator epoetin alfa after multiple subcutaneous administrations

> Added to model reports.

Processing article 26/114: Pharmacokinetics and bioequivalence of two cyclosporine oral solution formulations in cats

> Added to model reports.

Processing article 27/114: Conversion from twice- to once-daily tacrolimus in pediatric kidney recipients: a pharmacokinetic and bioequivalence study

> Added to model reports.

Processing article 28/114: Pharmacokinetic Bioequivalence, Safety, and Immunogenicity of DMB-3111, a Trastuzumab Biosimilar, and Trastuzumab in Healthy Japanese Adult Males: Results of a Randomized Trial

> Added to model reports.

Processing article 29/114: Acarbose bioequivalence: exploration of new pharmacodynamic parameters

> Added to model reports.

Processing article 30/114: Particle size and gastrointestinal absorption influence tiotropium pharmacokinetics: a pilot bioequivalence study of PUR0200 and Spiriva HandiHaler

> Added to model reports.

Processing article 31/114: Pharmacokinetic/pharmacodynamic assessment of a novel, pharmaceutical lipid-aspirin complex: results of a randomized, crossover, bioequivalence study

> Added to model reports.

Processing article 32/114: Immunomodulation profile of the biosimilar trastuzumab MYL-1401O in a bioequivalence phase I study

> Added to model reports.

Processing article 33/114: Bioequivalence of a new coated 15 mg primaquine formulation for malaria elimination

> Added to model reports.

Processing article 34/114: Medroxyprogesterone acetate: steady-state pharmacokinetics bioequivalence of two oral formulations

> Added to model reports.

Processing article 35/114: A Pharmacokinetic Bioequivalence Study of Fremanezumab Administered Subcutaneously Using an Autoinjector and a Prefilled Syringe

> Added to model reports.

Processing article 36/114: Comparative pharmacokinetics and bioequivalence of 145-mg fenofibrate formulations in healthy Korean participants

> Added to model reports.

Processing article 37/114: Saliva Versus Plasma Bioequivalence of Azithromycin in Humans: Validation of Class I Drugs of the Salivary Excretion Classification System

> Added to model reports.

Processing article 38/114: Pharmacokinetic interactions between chloroquine, sulfadoxine and pyrimethamine and their bioequivalence in a generic fixed-dose combination in healthy volunteers in Uganda

> Added to model reports.

Processing article 39/114: Bioequivalence Study of Tebipenem Pivoxil in Healthy Chinese Adults

> Added to model reports.

Processing article 40/114: Bioequivalence Between Generic and Branded Lamotrigine in People With Epilepsy: The EQUIGEN Randomized Clinical Trial

> Added to model reports.

Processing article 41/114: Absolute Oral Bioavailability and Bioequivalence of LSD Base and Tartrate in a Double-Blind, Placebo-Controlled, Crossover Study

> Added to model reports.

Processing article 42/114: Pharmacokinetics and bioequivalence evaluation of lenalidomide in Chinese patients with multiple myeloma

> Added to model reports.

Processing article 43/114: Steady state bioequivalence of generic and innovator formulations of stavudine, lamivudine, and nevirapine in HIV-infected Ugandan adults

> Added to model reports.

Processing article 44/114: Bioequivalence study of two formulations of bisoprolol fumarate film-coated tablets in healthy subjects

> Added to model reports.

Processing article 45/114: Single-Dose Bioequivalence of Two Mini Nicotine Lozenge Formulations

> Added to model reports.

Processing article 46/114: A Pharmacokinetic Bioequivalence Study Comparing Pirfenidone Tablet and Capsule Dosage Forms in Healthy Adult Volunteers

> Added to model reports.

Processing article 47/114: The Effect Of Food On The Pharmacokinetic Properties And Bioequivalence Of Two Formulations Of Levocetirizine Dihydrochloride In Healthy Chinese Volunteers

> Added to model reports.

Processing article 48/114: Pharmacokinetics, Bioequivalence and Safety Evaluation of Two Ticagrelor Tablets Under Fasting and Fed Conditions in Healthy Chinese Subjects

> Added to model reports.

Processing article 49/114: Bioequivalence of two esomeprazole magnesium enteric-coated formulations in healthy Chinese subjects

> Added to model reports.

Processing article 50/114: Comparative study on the bioavailability and bioequivalence of rifapentine capsules in humans

> Added to model reports.

Processing article 51/114: Clinical Bioequivalence of Wixela Inhub and Advair Diskus in Adults With Asthma

> Added to model reports.

Processing article 52/114: Bioequivalence and population pharmacokinetic modeling of two forms of antibiotic, cefuroxime lysine and cefuroxime sodium, after intravenous infusion in beagle dogs

> Added to model reports.

Processing article 53/114: Pharmacokinetics and Bioequivalence of Isavuconazole Administered as Isavuconazonium Sulfate Intravenous Solution via Nasogastric Tube or Orally in Healthy Subjects

> Added to model reports.

Processing article 54/114: Evaluation of bioequivalence of two oral formulations of olanzapine

> Added to model reports.

Processing article 55/114: Short Communication: Bioequivalence of Tenofovir and Emtricitabine After Coencapsulation with the Proteus Ingestible Sensor

> Added to model reports.

Processing article 56/114: Bioequivalence of oral and intravenous carbamazepine formulations in adult patients with epilepsy

> Added to model reports.

Processing article 57/114: Pharmacokinetics and bioequivalence assessment of optimized directly compressible Aceclofenac (100 mg) tablet formulation in healthy human subjects

> Added to model reports.

Processing article 58/114: Comparative Pharmacokinetics and Bioequivalence of Pour-On Ivermectin Formulations in Korean Hanwoo Cattle

> Added to model reports.

Processing article 59/114: Pharmacokinetics and bioequivalence evaluation of omeprazole and sodium bicarbonate dry suspensions in healthy Chinese volunteers

> Added to model reports.

Processing article 60/114: Comparative bioequivalence study between a novel matrix transdermal delivery system of fentanyl and a commercially available reservoir formulation

> Added to model reports.

Processing article 61/114: Demonstrating Bioequivalence for a Lumacaftor Monosubstance Formulation Versus Orkambi(®) (Lumacaftor/Ivacaftor) in Healthy Subjects

> Added to model reports.

Processing article 62/114: Fluorescence detection of tramadol in healthy Chinese volunteers by high-performance liquid chromatography and bioequivalence assessment

> Added to model reports.

Processing article 63/114: Bioequivalence study of two formulations of candesartan cilexetil tablet in healthy subjects under fasting conditions

> Added to model reports.

Processing article 64/114: Bioequivalence of eslicarbazepine acetate from two different sources of its active product ingredient in healthy subjects

> Added to model reports.

Processing article 65/114: Limited-sampling strategy models for itraconazole and hydroxy-itraconazole based on data from a bioequivalence study

> Added to model reports.

Processing article 66/114: Non-bioequivalence of sublingual nifedipine

> Added to model reports.

Processing article 67/114: Pharmacokinetic and bioequivalence study between two formulations of S-1 in Korean gastric cancer patients

> Added to model reports.

Processing article 68/114: Pharmacokinetics and bioequivalence evaluation of two fixed-dose tablet formulations of dihydroartemisinin and piperaquine in Vietnamese subjects

> Added to model reports.

Processing article 69/114: Bioequivalence and Pharmacokinetic Evaluation Study of Acetaminophen vs. Acetaminophen Plus Caffeine Tablets in Healthy Mexican Volunteers

> Added to model reports.

Processing article 70/114: Pharmacokinetic properties and bioequivalence of gefitinib 250 mg in healthy Korean male subjects

> Added to model reports.

Processing article 71/114: A 2-Part, Open-Label, Phase 1 Bioequivalence and Food-Effect Study of Ubrogepant in Healthy Adult Participants

> Added to model reports.

Processing article 72/114: Bioequivalence between innovator and generic tacrolimus in liver and kidney transplant recipients: A randomized, crossover clinical trial

> Added to model reports.

Processing article 73/114: Bioequivalence of two oral formulations of tebipenem pivoxil hydrobromide in healthy subjects

> Added to model reports.

Processing article 74/114: Bioequivalence of a Fixed-Dose Combination Tablet of the Complete Two-Drug Regimen of Dolutegravir and Rilpivirine for Treatment of HIV-1 Infection

> Added to model reports.

Processing article 75/114: Formulation and bioequivalence studies of choline alfoscerate tablet comparing with soft gelatin capsule in healthy male volunteers

> Added to model reports.

Processing article 76/114: Bioequivalence of two tablet formulations of cefpodoxime proxetil in beagle dogs

> Added to model reports.

Processing article 77/114: Preparation of altrenogest soft capsules and their bioequivalence in gilts

> Added to model reports.

Processing article 78/114: Allicin Bioavailability and Bioequivalence from Garlic Supplements and Garlic Foods

> Added to model reports.

Processing article 79/114: Lack of pharmacokinetic bioequivalence between generic and branded amoxicillin formulations. A post-marketing clinical study on healthy volunteers

> Added to model reports.

Processing article 80/114: Open-Label, Phase I, Pharmacokinetic Studies in Healthy Chinese Subjects to Evaluate the Bioequivalence and Food Effect of a Novel Formulation of Abiraterone Acetate Tablets

> Added to model reports.

Processing article 81/114: Bioequivalence study of modified-release gliclazide tablets in healthy volunteers

> Added to model reports.

Processing article 82/114: Pharmacokinetic bioequivalence of the fixed-dose combination of pertuzumab and trastuzumab administered subcutaneously using a handheld syringe or an on-body delivery system

> Added to model reports.

Processing article 83/114: Pharmacokinetics and Bioequivalence of a Generic Ticagrelor 90-mg Formulation Versus the Innovator Product in Healthy White Subjects Under Fasting Conditions

> Added to model reports.

Processing article 84/114: Bioequivalence Study of Rivastigmine 6 mg Capsules (Single Dose) in Healthy Volunteers

> Added to model reports.

Processing article 85/114: Bioequivalence and Bioavailability of an Orodispersible Tablet of Sildenafil Citrate in Healthy Chinese Male Subjects

> Added to model reports.

Processing article 86/114: A comparative evaluation of bioequivalence of Gan & Lee glargine U300 and Toujeo(®) in Chinese healthy male participants

> Added to model reports.

Processing article 87/114: Bioequivalence of Aripiprazole Oral Soluble Films and Orally Disintegrating Tablets in Healthy Participants: A Crossover Study

> Added to model reports.

Processing article 88/114: Bioequivalence and tolerability assessment of a novel intravenous ciclosporin lipid emulsion compared to branded ciclosporin in Cremophor ® EL

> Added to model reports.

Processing article 89/114: Pharmacokinetics and Bioequivalence of Two Fixed-Dose Combination Tablets of Valsartan/Amlodipine (80/5 Mg) in Healthy Chinese Subjects

> Added to model reports.

Processing article 90/114: Pharmacokinetics and Safety of Estradiol Valerate Tablet and Its Generic: A Phase 1 Bioequivalence Study in Healthy Chinese Postmenopausal Female Subjects

> Added to model reports.

Processing article 91/114: Variability of Skin Pharmacokinetic Data: Insights from a Topical Bioequivalence Study Using Dermal Open Flow Microperfusion

> Added to model reports.

Processing article 92/114: Bioequivalence of HX575 (recombinant human epoetin alfa) and a comparator epoetin alfa after multiple intravenous administrations: an open-label randomised controlled trial

> Added to model reports.

Processing article 93/114: The steady-state serum concentration of genistein aglycone is affected by formulation: a bioequivalence study of bone products

> Added to model reports.

Processing article 94/114: Application of absorption modeling to predict bioequivalence outcome of two batches of etoricoxib tablets

> Added to model reports.

Processing article 95/114: Bioequivalence and Pharmacokinetics of Low-Dose Anagrelide 0.5 mg Capsules in Healthy Volunteers

> Added to model reports.

Processing article 96/114: Batch-to-batch pharmacokinetic variability confounds current bioequivalence regulations: A dry powder inhaler randomized clinical trial

> Added to model reports.

Processing article 97/114: Bioequivalence evaluation of epinephrine autoinjectors with attention to rapid delivery

> Added to model reports.

Processing article 98/114: A study on the pharmacokinetic bioequivalence of oral tablet formulations of riluzole among healthy volunteers utilizing HPLC-MS/MS

> Added to model reports.

Processing article 99/114: Effect of excipients on the particle size of precipitated pioglitazone in the gastrointestinal tract: impact on bioequivalence

> Added to model reports.

Processing article 100/114: Adjustment of the area under the concentration curve by terminal rate constant for bioequivalence assessment in a parallel-group study of lamotrigine

> Added to model reports.

Processing article 101/114: Pharmacokinetics and bioequivalence of Withania somnifera (Ashwagandha) extracts - A double blind, crossover study in healthy adults

> Added to model reports.

Processing article 102/114: Formulation and bioequivalence of two valsartan tablets after a single oral administration

> Added to model reports.

Processing article 103/114: Pharmacogenetic Variants Associated with Fluoxetine Pharmacokinetics from a Bioequivalence Study in Healthy Subjects

> Added to model reports.

Processing article 104/114: Bioequivalence of perampanel fine granules and tablets in healthy Japanese subjects

> Added to model reports.

Processing article 105/114: Confocal Raman Spectroscopy for Assessing Bioequivalence of Topical Formulations

> Added to model reports.

Processing article 106/114: Bioequivalence and Pharmacokinetic Evaluation of Two Metformin Hydrochloride Tablets Under Fasting and Fed Conditions in Healthy Chinese Volunteers

> Added to model reports.

Processing article 107/114: Bioequivalence study of two formulations of lurasidone film coated tablets in healthy subjects under fed conditions

> Added to model reports.

Processing article 108/114: Bioequivalence and Food Effect Assessment of 2 Fixed-Dose Combination Formulations of Dolutegravir and Lamivudine

> Added to model reports.

Processing article 109/114: Bioequivalence study of donepezil hydrochloride tablets in healthy male volunteers

> Added to model reports.

Processing article 110/114: Bioequivalence and Food Effect Assessment of Two Fixed-Dose Combination Formulations of Telmisartan-Hydrochlorothiazide Tablets in Chinese Healthy Subjects

> Added to model reports.

Processing article 111/114: Bioequivalence and pharmacodynamics of a generic dabigatran etexilate capsule in healthy Chinese subjects under fasting and fed conditions

> Added to model reports.

Processing article 112/114: Bioequivalence study of three ibuprofen formulations after single dose administration in healthy volunteers

> Added to model reports.

Processing article 113/114: Comparative Pharmacokinetics, Bioequivalence and Safety Study of Two Recombinant Human Chorionic Gonadotropin Injections in Healthy Chinese Subjects

> Added to model reports.

Processing article 114/114: Bioequivalence study of fluticasone propionate nebuliser suspensions in healthy Chinese subjects

> Added to model reports.

Total price for extracting content from 114 papers: $0.262

### Total costs

Now we can calculate the total costs for the flagging and the extraction of structured information from all suitable publications.

In [13]:
# define prices for these calls (in USD)
total_price = total_price_flag + total_price_content
print(f"Total price of this notebook execution: ${total_price:.3f}")

Total price of this notebook execution: $0.314